# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: location.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0elocation.proto\x12\x07\x63ontext\"\x1a\n\x08Location\x12\x0e\n\x06offset\x18\x01 \x01(\x04\"&\n\x13SetLocationResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2\x88\x01\n\x0cLocationSync\x12>\n\x0bsetLocation\x12\x11.context.Location\x1a\x1c.context.SetLocationResponse\x12\x38\n\x0csyncLocation\x12\x11.context.Location\x1a\x11.context.Location(\x01\x30\x01\x42\x15\n\x13\x65mber.grpc.locationb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'location_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\023ember.grpc.location'
  _LOCATION._serialized_start=27
  _LOCATION._serialized_end=53
  _SETLOCATIONRESPONSE._serialized_start=55
  _SETLOCATIONRESPONSE._serialized_end=93
  _LOCATIONSYNC._serialized_start=96
  _LOCATIONSYNC._serialized_end=232
# @@protoc_insertion_point(module_scope)
