# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import ember.plugin.ghidra.location_pb2 as location__pb2


class LocationSyncStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.setLocation = channel.unary_unary(
                '/context.LocationSync/setLocation',
                request_serializer=location__pb2.Location.SerializeToString,
                response_deserializer=location__pb2.SetLocationResponse.FromString,
                )
        self.syncLocation = channel.stream_stream(
                '/context.LocationSync/syncLocation',
                request_serializer=location__pb2.Location.SerializeToString,
                response_deserializer=location__pb2.Location.FromString,
                )


class LocationSyncServicer(object):
    """Missing associated documentation comment in .proto file."""

    def setLocation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def syncLocation(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LocationSyncServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'setLocation': grpc.unary_unary_rpc_method_handler(
                    servicer.setLocation,
                    request_deserializer=location__pb2.Location.FromString,
                    response_serializer=location__pb2.SetLocationResponse.SerializeToString,
            ),
            'syncLocation': grpc.stream_stream_rpc_method_handler(
                    servicer.syncLocation,
                    request_deserializer=location__pb2.Location.FromString,
                    response_serializer=location__pb2.Location.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'context.LocationSync', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class LocationSync(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def setLocation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/context.LocationSync/setLocation',
            location__pb2.Location.SerializeToString,
            location__pb2.SetLocationResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def syncLocation(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/context.LocationSync/syncLocation',
            location__pb2.Location.SerializeToString,
            location__pb2.Location.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
